version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  detailed:
    format: '%(asctime)s [%(levelname)s] %(name)s:%(lineno)d: %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  file_handler:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: detailed
    filename: logs/experiment.log
    when: midnight
    interval: 1
    backupCount: 30
    encoding: utf8

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/error.log
    maxBytes: 10485760  # 10MB
    backupCount: 20
    encoding: utf8

  performance_handler:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: detailed
    filename: logs/performance.log
    when: H
    interval: 1
    backupCount: 48
    encoding: utf8

loggers:
  experiment:
    level: INFO
    handlers: [console, file_handler, error_file_handler]
    propagate: false

  database:
    level: INFO
    handlers: [console, file_handler, error_file_handler]
    propagate: false

  image_processing:
    level: INFO
    handlers: [console, file_handler, error_file_handler]
    propagate: false

  performance:
    level: INFO
    handlers: [performance_handler]
    propagate: false

root:
  level: INFO
  handlers: [console, file_handler]
